import Header from '@/components/Header'
import './globals.css'
import { Sora } from 'next/font/google'
import Footer from '@/components/Footer'

const inter = Sora({ subsets: ['latin'] })

export const metadata = {
  title: 'Nextjs Ecommerce Store',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
        
      <body className={inter.className}>
       
          <Header/>
          {children}
          <Footer/>
     
          </body>
    </html>
  )
}
